-- MySQL Script generated by MySQL Workbench
-- 12/10/14 12:43:24
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema juliepro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `juliepro` ;
CREATE SCHEMA IF NOT EXISTS `juliepro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `juliepro` ;

-- -----------------------------------------------------
-- Table `juliepro`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juliepro`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `juliepro`.`Utilisateur` (
  `utilisateurID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `noTel` VARCHAR(45) NOT NULL,
  `noCell` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `codePostal` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `dateInscription` DATETIME NOT NULL,
  `courriel` VARCHAR(45) NOT NULL,
  `statut` INT NOT NULL,
  `entraineurID` INT NOT NULL,
  PRIMARY KEY (`utilisateurID`),
  INDEX `fk_Utilisateur_Utilisateur_idx` (`entraineurID` ASC),
  CONSTRAINT `fk_Utilisateur_Utilisateur`
    FOREIGN KEY (`entraineurID`)
    REFERENCES `juliepro`.`Utilisateur` (`utilisateurID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juliepro`.`categorieNourriture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juliepro`.`categorieNourriture` ;

CREATE TABLE IF NOT EXISTS `juliepro`.`categorieNourriture` (
  `categorieID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categorieID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juliepro`.`Alimentation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juliepro`.`Alimentation` ;

CREATE TABLE IF NOT EXISTS `juliepro`.`Alimentation` (
  `alimentationID` INT NOT NULL AUTO_INCREMENT,
  `nomRepas` VARCHAR(45) NOT NULL,
  `calorieIngere` INT NOT NULL,
  `date` DATE NOT NULL,
  `categorieID` INT NOT NULL,
  `clientID` INT NOT NULL,
  PRIMARY KEY (`alimentationID`),
  INDEX `fk_Alimentation_catégorieNourriture1_idx` (`categorieID` ASC),
  INDEX `fk_Alimentation_Utilisateur1_idx` (`clientID` ASC),
  CONSTRAINT `fk_Alimentation_catégorieNourriture1`
    FOREIGN KEY (`categorieID`)
    REFERENCES `juliepro`.`categorieNourriture` (`categorieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alimentation_Utilisateur1`
    FOREIGN KEY (`clientID`)
    REFERENCES `juliepro`.`Utilisateur` (`utilisateurID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juliepro`.`Entrainement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juliepro`.`Entrainement` ;

CREATE TABLE IF NOT EXISTS `juliepro`.`Entrainement` (
  `entrainementID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`entrainementID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juliepro`.`Resultat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juliepro`.`Resultat` ;

CREATE TABLE IF NOT EXISTS `juliepro`.`Resultat` (
  `resultatID` INT NOT NULL AUTO_INCREMENT,
  `FQMax` INT NOT NULL,
  `VO2Max` INT NOT NULL,
  `calorieBrulee` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `entrainementID` INT NOT NULL,
  `clientID` INT NOT NULL,
  PRIMARY KEY (`resultatID`),
  INDEX `fk_Résultat_Entrainement1_idx` (`entrainementID` ASC),
  INDEX `fk_Résultat_Utilisateur1_idx` (`clientID` ASC),
  CONSTRAINT `fk_Résultat_Entrainement1`
    FOREIGN KEY (`entrainementID`)
    REFERENCES `juliepro`.`Entrainement` (`entrainementID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Résultat_Utilisateur1`
    FOREIGN KEY (`clientID`)
    REFERENCES `juliepro`.`Utilisateur` (`utilisateurID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juliepro`.`Conseil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juliepro`.`Conseil` ;

CREATE TABLE IF NOT EXISTS `juliepro`.`Conseil` (
  `conseilID` INT NOT NULL AUTO_INCREMENT,
  `texte` TEXT NOT NULL,
  `entraineurID` INT NOT NULL,
  `clientID` INT NOT NULL,
  PRIMARY KEY (`conseilID`),
  INDEX `fk_Conseil_Utilisateur1_idx` (`entraineurID` ASC),
  INDEX `fk_Conseil_Utilisateur2_idx` (`clientID` ASC),
  CONSTRAINT `fk_Conseil_Utilisateur1`
    FOREIGN KEY (`entraineurID`)
    REFERENCES `juliepro`.`Utilisateur` (`utilisateurID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conseil_Utilisateur2`
    FOREIGN KEY (`clientID`)
    REFERENCES `juliepro`.`Utilisateur` (`utilisateurID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
